interface=wlan0
driver=nl80211
ssid=Raspberry-pi_AP
hw_mode=g
channel=6

country_code=CR
ieee80211d=1

auth_algs=1
ignore_broadcast_ssid=0

wpa=2
wpa_passphrase=raspberry123
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
