# -*- coding: utf-8 -*-
"""convert_tflite.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jAWXZ3AmgZ0639IMFlkDZ_GSRq_Jq4EP
"""

!cp -r /content/drive/MyDrive/dataset /content/
!mkdir -p /content/dataset
!tar -xf /content/dataset/dataset.tar -C /content/dataset

import tensorflow as tf
import numpy as np

# cargar modelo sin compilar
model = tf.keras.models.load_model(
    '/content/drive/MyDrive/model/model_epoch_063.keras',
    compile=False
)

# convertidor
converter = tf.lite.TFLiteConverter.from_keras_model(model)

# optimización
converter.optimizations = [tf.lite.Optimize.DEFAULT]

# cuantización float16
converter.target_spec.supported_types = [tf.float16]

print("Convirtiendo modelo...")

tflite_model = converter.convert()

output_path = '/content/drive/MyDrive/models/lunar_rpi5_float16.tflite'

with open(output_path, 'wb') as f:
    f.write(tflite_model)

print("Modelo convertido")
print("Tamaño:", len(tflite_model)/(1024*1024), "MB")

import tensorflow as tf
import numpy as np
import cv2
import os

MODEL_PATH = "/content/drive/MyDrive/model/model_epoch_063.keras"
OUTPUT_PATH = "/content/drive/MyDrive/models/lunar_rpi5_int8.tflite"

IMG_H = 240
IMG_W = 320

# cargar modelo
model = tf.keras.models.load_model(MODEL_PATH, compile=False)

# ==============================
# dataset representativo
# ==============================

DATASET_DIR = "/content/dataset/color"

image_paths = [
    os.path.join(DATASET_DIR,x)
    for x in os.listdir(DATASET_DIR)
    if x.endswith(".jpg") or x.endswith(".png")
][:500]   # 100-500 imágenes es suficiente

def representative_dataset():

    for path in image_paths:

        img = cv2.imread(path)
        img = cv2.resize(img,(IMG_W,IMG_H))

        img = img.astype(np.float32) / 255.0
        img = np.expand_dims(img,0)

        yield [img]

# ==============================
# conversión
# ==============================

converter = tf.lite.TFLiteConverter.from_keras_model(model)

converter.optimizations = [tf.lite.Optimize.DEFAULT]

converter.representative_dataset = representative_dataset

converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS_INT8
]

converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8

print("Convirtiendo modelo a INT8...")

tflite_model = converter.convert()

with open(OUTPUT_PATH,"wb") as f:
    f.write(tflite_model)

print("Modelo exportado:", OUTPUT_PATH)
print("Tamaño:", len(tflite_model)/(1024*1024), "MB")